### ISSUE TITLE
ability to transparent replace original

### ISSUE THREAD

**Issue by vtolstov** [VictoriaMetrics/metrics#1]
nice package, thanks.
does it possible to transparently replace github.com/prometheus/client_golang/prometheus
with github.com/VictoriaMetrics/metrics via go.mod ?
I don't want to change import paths in code, but prefer to override it via go.mod

**Comment by valyala** [comment]
This would be hard, since [the API](https://godoc.org/github.com/VictoriaMetrics/metrics) is quite different.

**Comment by vtolstov** [comment]
But if you provide compatible interfaces with original package, but not needed function returns nothing?

**Comment by valyala** [comment]
It is possible to create a thin wrapper for `github.com/VictoriaMetrics/metrics`, which would expose the same API as `github.com/prometheus/client_golang/prometheus`, but this should be done in a separate package, so this package remains clear.

**Comment by vtolstov** [comment]
ok, thanks!
