### ISSUE TITLE
vmrange histograms in stock Prometheus?

### ISSUE THREAD

**Issue by illotum** [VictoriaMetrics/metrics#10]
Plenty of services came to expect Prometheus style of histograms. 

Considering how hard it is to pull off a single day migration, what can orgs do to make vmrange histograms work in existing dashboards? 

Do you have a way to show data without VictoriaMetrics extensions?

**Comment by valyala** [comment]
Unfortunately Prometheus doesn't support [VictoriaMetrics histograms](https://medium.com/@valyala/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350). I'd suggest creating a feature request at [Prometheus issue tracker](https://github.com/prometheus/prometheus/issues) for adding support for VictoriaMetrics histograms.

**Comment by illotum** [comment]
Understood, cheers!
