### ISSUE TITLE
Summary Unregister is partial

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/metrics#14]
Call `Unregister` method for `summary` metric does only partial removing, so re-registering of metric is impossible:
```
s := NewSet()
s.NewSummary("summary")
s.UnregisterMetric("summary")
s.NewSummary("summary") // this fails 
```

**Comment by valyala** [comment]
This issue has been fixed in [v1.12.2](https://github.com/VictoriaMetrics/metrics/tree/v1.12.2)
