### ISSUE TITLE
process_* metrics on windows build

### ISSUE THREAD

**Issue by krzysion** [VictoriaMetrics/metrics#23]
Please add process_* metrics on windows build.

**Comment by valyala** [comment]
The `process_*` metrics have been added on Windows build in the commit ae1e9d8058de94e5622ccee515ece7992d67d209 , which has been included in the tag [v1.24.0](https://github.com/VictoriaMetrics/metrics/tree/v1.24.0). Closing this feature request as done.

@krzysion , feel free re-opening this issue or creating new one if you need additional `process_*` metrics on Windows.
