### ISSUE TITLE
push with authorization

### ISSUE THREAD

**Issue by TomasVojacek** [VictoriaMetrics/metrics#36]
It would be great if metric push allowed to add authorization header like "Bearer xxxxx".
This will allow push data to managed instance on victoriametrics.com

**Comment by hagen1778** [comment]
Hi @TomasVojacek! The option to set HTTP headers was added in https://github.com/VictoriaMetrics/metrics/pull/53 via PushConfig.
See example of using the  the PushConfig here https://github.com/VictoriaMetrics/metrics/blob/42c28a8486fb3f180026c0b2c90643ac9e91951e/push_example_test.go#L14-L35

**Comment by TomasVojacek** [comment]
Thank you

**Comment by valyala** [comment]
FYI, the pull request https://github.com/VictoriaMetrics/metrics/pull/53 has been reverted and substituted with more clear API in the tag [v1.26.0](https://github.com/VictoriaMetrics/metrics/tree/v1.26.0). Now the following code can be used for initialization of metrics push with `Authorization: Bearer xxx` request headers:

```go
import "github.com/VictoriaMetrics/metrics"

opts := &metrics.PushOptions{
    Headers: []string{"Authorization: Bearer xxx"},
}
if err := metrics.InitPushWithOptions(context.Background(), pushURL, pushInterval, true, opts); err != nil {
    log.Fatalf("cannot initialize metrics push: %s", err)
}
```

See the docs for `metrics.InitPushWithOptions` function:

```
func InitPushWithOptions(ctx context.Context, pushURL string, interval time.Duration, pushProcessMetrics bool, opts *PushOptions) error
    InitPushWithOptions sets up periodic push for globally registered metrics to
    the given pushURL with the given interval.

    The periodic push is stopped when ctx is canceled.

    If pushProcessMetrics is set to true, then 'process_*' and `go_*` metrics
    are also pushed to pushURL.

    opts may contain additional configuration options if non-nil.

    The metrics are pushed to pushURL in Prometheus text exposition format. See
    https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#text-based-format

    It is recommended pushing metrics to
    /api/v1/import/prometheus endpoint according to
    https://docs.victoriametrics.com/#how-to-import-data-in-prometheus-exposition-format

    It is OK calling InitPushWithOptions multiple times with different pushURL -
    in this case metrics are pushed to all the provided pushURL urls.
```
