### ISSUE TITLE
Support of authorization for setInitPush

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/metrics#52]
That would be awesome if i can set Bearer token for setInitPush URL when I need to push data to some protected SaaSs

as additional we can add Config struct and initPushWithConfig method where we can specify all future params

-------------------

moved from https://github.com/VictoriaMetrics/metricsql/issues/19

**Comment by valyala** [comment]
Closing as duplicate of https://github.com/VictoriaMetrics/metrics/issues/36
