### ISSUE TITLE
Support additional golang runtime metrics.

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/metrics#54]
It'd be great to have following metrics:

https://pkg.go.dev/runtime/metrics
```
/sched/latencies:seconds
	Distribution of the time goroutines have spent in the scheduler
	in a runnable state before actually running. Bucket counts
	increase monotonically.

/sync/mutex/wait/total:seconds
	Approximate cumulative time goroutines have spent blocked
	on a sync.Mutex or sync.RWMutex. This metric is useful for
	identifying global changes in lock contention. Collect a mutex
	or block profile using the runtime/pprof package for more
	detailed contention data.

```

**Comment by hagen1778** [comment]
@f41gh7 would you like to work on this?

**Comment by valyala** [comment]
The following additional Go runtime metrics are exposed by `github.com/VictoriaMetrics/metrics` package starting from [v1.25.3](https://github.com/VictoriaMetrics/metrics/tree/v1.25.3):

  * `go_sched_latencies_seconds` - the [histogram](https://docs.victoriametrics.com/keyConcepts.html#histogram), which shows the time goroutines have spent in runnable state before actually running. Big values point to the lack of CPU time for the current workload.
  * `go_mutex_wait_seconds_total` - the [counter](https://docs.victoriametrics.com/keyConcepts.html#counter), which shows the total time spent by goroutines waiting for locked mutex. Big values point to mutex contention issues.
  * `go_gc_cpu_seconds_total` - the [counter](https://docs.victoriametrics.com/keyConcepts.html#counter), which shows the total CPU time spent by Go garbage collector.
  * `go_gc_mark_assist_cpu_seconds_total` - the [counter](https://docs.victoriametrics.com/keyConcepts.html#counter), which shows the total CPU time spent by goroutines in GC mark assist state.
  * `go_gc_pauses_seconds` - the [histogram](https://docs.victoriametrics.com/keyConcepts.html#histogram), which shows the duration of GC pauses.
  * `go_scavenge_cpu_seconds_total` - the [counter](https://docs.victoriametrics.com/keyConcepts.html#counter), which shows the total CPU time spent by Go runtime for returning memory to the Operating System.
  * `go_memlimit_bytes` - the value of [GOMEMLIMIT](https://pkg.go.dev/runtime#hdr-Environment_Variables) environment variable.

These metrics will be available in the next release of VictoriaMetrics - see  https://github.com/VictoriaMetrics/VictoriaMetrics/commit/8eddccfbb41a916db59e4320eb62ec7f78eea818 .

Closing this feature request as done.

**Comment by valyala** [comment]
New metrics mentioned [here](https://github.com/VictoriaMetrics/metrics/issues/54#issuecomment-1832896703) are available in VictoriaMetrics components starting from [v1.96.0 release](https://docs.victoriametrics.com/CHANGELOG.html).
