### ISSUE TITLE
bug: set.WritePrometheus doesn't take exposeProcessMetrics param

### ISSUE THREAD

**Issue by mr-karan** [VictoriaMetrics/metrics#7]
Is there any reason that [set.WritePrometheus](https://github.com/VictoriaMetrics/metrics/blob/master/set.go#L32) doesn't take `exposeProcessMetrics` param but [metrics.WritePrometheus](https://github.com/VictoriaMetrics/metrics/blob/master/metrics.go#L41) does? Ideally both methods should be consistent.

Thanks!

**Comment by valyala** [comment]
`metrics.WritePrometheus` accepts `exposeProcessMetrics` param due to historical reasons. I think it would be better exporting `WriteProcessMetrics(w io.Writer)` function instead. This function could be used for exporting process metrics to `w`.

**Comment by lammel** [comment]
A new function `WriteProcessMetrics(w io.Writer)` has been merged with PR #6. 

So with the next release you can simply use this helper in addition to the metrics written by the set.

Example:
```go
http.HandleFunc("/metrics", func(w http.ResponseWriter, req *http.Request) {
         mySet.WritePrometheus(w)
         metrics.WriteProcessMetrics(w)
})
```

So this will give us the required flexibility without duplicating code.

**Comment by mr-karan** [comment]
Thanks for this, I'll check it out. But I was wondering, whether `set.WriteProcessMetrics` can be exposed too. I create a new metric set in my code and I want to avoid any global variables generally. So if that makes sense, I can send a PR for the same.

**Comment by lammel** [comment]
The example above is from my real world code. `metrics` is the package, so it is no global variable but rather from `import github.com/VictoriaMetrics/metrics`.

So you *can* already use the `myset.WritePrometheus(w)` to write your own metrics and then also write the current process metrics using `metrics.WriteProcessMetrics(w)` which is being made available by the metrics package.

So no PR needed I guess.

**Comment by mr-karan** [comment]
Got it. Thanks :)
